# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njDqh5vGrixX9hFe4uXFzMDwtBDpNQgC
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open("sales_revenue_model.pkl", "rb") as file:
    model = pickle.load(file)

# Streamlit UI
st.title("Sales Revenue Prediction Dashboard")
st.write("Enter the values to predict revenue.")

# User input fields
unit_price = st.number_input("Unit Price ($)", min_value=0.0, value=10.0)
quantity = st.number_input("Quantity", min_value=1, value=1)
shipping_fee = st.number_input("Shipping Fee ($)", min_value=0.0, value=5.0)

# Button to predict revenue
if st.button("Predict Revenue"):
    # Prepare input features
    input_data = np.array([[unit_price, quantity, shipping_fee]])  # Add necessary encoded columns
    prediction = model.predict(input_data)[0]

    # Show prediction
    st.success(f"Predicted Total Price: ${prediction:.2f}")